# Generated by Django 4.2.6 on 2023-10-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoemart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('1', 'Nike'), ('2', 'Adidas'), ('3', 'NB')], max_length=10, verbose_name='Category'),
        ),
    ]
